name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  schedule:
    # Runs every Monday at 8:00 UTC (4:00 Eastern)
    - cron: '0 8 * * 1'
  push: # Run workflow when this file is updated on dev
    branches:
      - dev
    paths:
      - .github/workflows/semgrep.yml
jobs:
  setup:
    name: Install pdm and generate requirements.txt
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pdm
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: ./pyproject.toml
          cache-dependency-path: |
            ./pdm.lock
      - name: Generate requirements txt
        run: |
          pdm init
          pdm add certifi
          pdm export -o requirements.txt
      - name: Upload Requirements File as Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: requirements
          path: ${{ github.workspace }}/requirements.txt
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-22.04
    needs: setup
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4.0.0
        with:
          name: requirements
          path: ${{ github.workspace }}/requirements.txt
      - name: Run Semgrep CI
        working-directory: ${{ github.workspace }}
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: semgrep ci --no-git-ignore
